export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const TOGGLE_FAV_MOVIE = 'TOGGLE_FAV_MOVIE'
export const SET_FAV_MOVIES_SHOW = 'SET_FAV_MOVIES_SHOW'

export const SET_REC_MOOVIES = 'SET_REC_MOOVIES'
export const SET_NEW_MOOVIES = 'SET_NEW_MOOVIES'